modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
issueTrackerURL = "https://discord.gg/pHren9yxzW"
logoFile = ""

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = ""
authors = "${mod_authors}"
description = ''''''

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"